import { execFileSync } from 'child_process'
import { join } from 'path'

export class GitManager {
  static branchName(taskId: string, title: string): string {
    const slug = title
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
    const full = `feature/${taskId}-${slug}`
    return full.substring(0, 80)
  }

  static worktreePath(repoPath: string, branch: string): string {
    const safeBranch = branch.replace(/\//g, '-')
    return join(repoPath, '.worktrees', safeBranch)
  }

  static prBody(opts: {
    title: string
    description: string
    executionId: string
    taskId: string
  }): string {
    return [
      `## ${opts.title}`,
      '',
      opts.description,
      '',
      '## Context',
      '',
      `- **Execution:** ${opts.executionId}`,
      `- **Task:** ${opts.taskId}`,
      '',
      '---',
      'Generated by Gaud Orchestrator',
    ].join('\n')
  }

  static createWorktree(repoPath: string, branch: string, baseBranch = 'main'): string {
    const wtPath = GitManager.worktreePath(repoPath, branch)
    try {
      execFileSync('git', ['branch', branch, baseBranch], { cwd: repoPath, encoding: 'utf-8' })
    } catch {
      // Branch may already exist
    }
    execFileSync('git', ['worktree', 'add', wtPath, branch], { cwd: repoPath, encoding: 'utf-8' })
    return wtPath
  }

  static removeWorktree(repoPath: string, branch: string): void {
    const wtPath = GitManager.worktreePath(repoPath, branch)
    try {
      execFileSync('git', ['worktree', 'remove', wtPath, '--force'], { cwd: repoPath, encoding: 'utf-8' })
    } catch {
      // Worktree may not exist
    }
  }

  static pushBranch(repoPath: string, branch: string): void {
    execFileSync('git', ['push', '-u', 'origin', branch], { cwd: repoPath, encoding: 'utf-8' })
  }

  static createPR(opts: { repoPath: string; branch: string; title: string; body: string }): string {
    const result = execFileSync(
      'gh', ['pr', 'create', '--title', opts.title, '--body', opts.body, '--head', opts.branch],
      { cwd: opts.repoPath, encoding: 'utf-8' },
    )
    return result.trim()
  }
}
